# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1e4c177c5fa4be2e62f6e33ed74a589025dd3bcbf807716dfd2b209aa8e86607ed6af2d1b48c4725885255182a92d6b331e841010853e7b3cb8bfbfadf590a6

test:
  secret_key_base: 651ab3b2d35bea7429042de623065e019c0b05315a9236c84a600ac11cfe45317eb24cddcc079f77b5bcc7a1056667a00bbc5e2e1c3662ab72e5aaa827cef60a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
